# Generated by Django 3.2 on 2021-04-28 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MarioShareModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coursetitle', models.CharField(max_length=100)),
                ('courseid', models.CharField(max_length=11)),
                ('comment', models.TextField()),
                ('good', models.IntegerField(blank=True, default=0, null=True)),
                ('favorite', models.IntegerField(blank=True, default=0, null=True)),
            ],
        ),
    ]
