# Generated by Django 3.2 on 2021-04-30 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marioshareapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mariosharemodel',
            name='coursecreater',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
