# Generated by Django 3.2 on 2021-04-30 11:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('marioshareapp', '0002_mariosharemodel_coursecreater'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mariosharemodel',
            old_name='coursecreater',
            new_name='coursemaker',
        ),
    ]
