# Generated by Django 3.2 on 2021-04-30 12:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('marioshareapp', '0003_rename_coursecreater_mariosharemodel_coursemaker'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mariosharemodel',
            old_name='courseid',
            new_name='Course_ID',
        ),
        migrations.RenameField(
            model_name='mariosharemodel',
            old_name='coursetitle',
            new_name='Course_Title',
        ),
        migrations.RenameField(
            model_name='mariosharemodel',
            old_name='comment',
            new_name='Description',
        ),
        migrations.RenameField(
            model_name='mariosharemodel',
            old_name='coursemaker',
            new_name='Maker_Name',
        ),
    ]
