# Generated by Django 3.2 on 2021-04-30 12:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('marioshareapp', '0004_auto_20210430_2101'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mariosharemodel',
            old_name='Description',
            new_name='comment',
        ),
        migrations.RenameField(
            model_name='mariosharemodel',
            old_name='Course_ID',
            new_name='courseid',
        ),
        migrations.RenameField(
            model_name='mariosharemodel',
            old_name='Maker_Name',
            new_name='coursemaker',
        ),
        migrations.RenameField(
            model_name='mariosharemodel',
            old_name='Course_Title',
            new_name='coursetitle',
        ),
    ]
