# Generated by Django 3.2 on 2021-05-01 03:13

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('marioshareapp', '0005_auto_20210430_2106'),
    ]

    operations = [
        migrations.AddField(
            model_name='mariosharemodel',
            name='courseimage',
            field=models.FileField(null=True, upload_to='media/'),
        ),
        migrations.AddField(
            model_name='mariosharemodel',
            name='post_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 5, 1, 3, 13, 12, 240011, tzinfo=utc)),
        ),
    ]
