# Generated by Django 3.2 on 2021-05-01 03:19

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('marioshareapp', '0006_auto_20210501_1213'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mariosharemodel',
            name='post_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
