# Generated by Django 3.2 on 2021-05-01 03:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marioshareapp', '0008_alter_mariosharemodel_courseimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mariosharemodel',
            name='courseimage',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
