# Generated by Django 3.2 on 2021-05-01 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marioshareapp', '0009_alter_mariosharemodel_courseimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mariosharemodel',
            name='courseimage',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
