# Generated by Django 3.2 on 2021-05-02 06:07

from django.db import migrations
import embed_video.fields


class Migration(migrations.Migration):

    dependencies = [
        ('marioshareapp', '0010_alter_mariosharemodel_courseimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='mariosharemodel',
            name='coursevideo',
            field=embed_video.fields.EmbedVideoField(null=True),
        ),
    ]
