# Generated by Django 3.2 on 2021-05-05 03:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marioshareapp', '0011_mariosharemodel_coursevideo'),
    ]

    operations = [
        migrations.AddField(
            model_name='mariosharemodel',
            name='contributer',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
