# Generated by Django 3.2 on 2021-05-05 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marioshareapp', '0014_alter_mariosharemodel_contributer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mariosharemodel',
            name='contributer',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
