# Generated by Django 3.2 on 2021-05-08 02:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('marioshareapp', '0016_categorymodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='mariosharemodel',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='marioshareapp.categorymodel'),
            preserve_default=False,
        ),
    ]
