# Generated by Django 3.2 on 2021-05-08 02:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('marioshareapp', '0017_mariosharemodel_category'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CategoryModel',
            new_name='CourseCategory',
        ),
        migrations.RenameField(
            model_name='mariosharemodel',
            old_name='category',
            new_name='coursecategory',
        ),
    ]
