# Generated by Django 3.2 on 2021-05-08 03:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marioshareapp', '0018_auto_20210508_1143'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coursecategory',
            name='name',
            field=models.CharField(choices=[('danger', 'high'), ('warning', 'normal')], max_length=50),
        ),
    ]
