# Generated by Django 3.2 on 2021-05-08 03:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marioshareapp', '0019_alter_coursecategory_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mariosharemodel',
            name='coursecategory',
        ),
        migrations.AlterField(
            model_name='coursecategory',
            name='name',
            field=models.CharField(max_length=50),
        ),
    ]
