# Generated by Django 3.2 on 2021-05-12 03:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marioshareapp', '0023_likedmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='mariosharemodel',
            name='like_set',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
