# Generated by Django 3.2 on 2021-05-12 11:29

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('marioshareapp', '0026_mariosharemodel_like_set'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mariosharemodel',
            name='like_set',
        ),
        migrations.AddField(
            model_name='mariosharemodel',
            name='like',
            field=models.ManyToManyField(blank=True, related_name='likes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='mariosharemodel',
            name='slug',
            field=models.SlugField(default=1),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='LikedModel',
        ),
    ]
