# Generated by Django 3.2 on 2021-05-12 11:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('marioshareapp', '0027_auto_20210512_2029'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mariosharemodel',
            name='like',
        ),
        migrations.RemoveField(
            model_name='mariosharemodel',
            name='slug',
        ),
    ]
