# Generated by Django 3.2 on 2021-05-20 00:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marioshareapp', '0030_alter_mariosharemodel_courseimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mariosharemodel',
            name='courseimage',
            field=models.ImageField(blank=True, default='../media/default_thumbnail.png', null=True, upload_to='media'),
        ),
    ]
